In [1]:
import pickle

In [2]:
import pandas as pd

In [3]:
final_scaled_df = pd.read_pickle("sprint1_output.pkl")

In [4]:
df=final_scaled_df
df.head()

,ord_mood__mood,ord_env__work_environment,ohe__work_type_Manual,ohe__work_type_Office,ohe__work_type_Remote,ohe__work_type_Student,remainder__number_of_decisions_made,remainder__context_switch_count,remainder__notifications_received,remainder__screen_time_min,...,remainder__task_complexity_avg,remainder__caffeine_mg,remainder__break_frequency,remainder__sleep_hours,remainder__deep_sleep_pct,remainder__hydration_l,remainder__noise_level_db,remainder__temperature_c,remainder__workload_score,remainder__mental_tiredness_score
0,2.0,1.0,0.0,0.0,1.0,0.0,-0.926224,2.120693,0.620176,-0.775544,...,0.763712,0.061978,-1.488002,0.729944,1.297849,0.229127,0.597886,-1.078432,-1.235038,22.17
1,0.0,2.0,0.0,0.0,1.0,0.0,0.176518,0.358696,0.127210,-0.335477,...,0.508233,-0.594295,-0.496573,0.220741,-0.201019,-0.105987,-0.916355,-1.449124,-0.565300,25.35
2,2.0,0.0,0.0,1.0,0.0,0.0,-0.650538,-1.403301,-1.228447,0.626205,...,2.296586,0.569898,0.494855,-1.059983,1.470731,0.039714,-0.601312,1.145723,1.134804,34.36
3,2.0,0.0,1.0,0.0,0.0,0.0,-0.650538,0.006296,-2.460862,-0.012957,...,-0.360396,0.421545,-0.992288,1.216002,-2.607937,-0.003996,-0.072852,0.269541,-0.153154,11.92
4,2.0,1.0,1.0,0.0,0.0,0.0,-2.304651,0.006296,0.373693,-0.452290,...,1.274670,0.693107,-0.000859,0.452197,0.361266,0.753653,1.329600,0.404338,1.443914,37.45

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ord_mood__mood                       15000 non-null  float64
 1   ord_env__work_environment            15000 non-null  float64
 2   ohe__work_type_Manual                15000 non-null  float64
 3   ohe__work_type_Office                15000 non-null  float64
 4   ohe__work_type_Remote                15000 non-null  float64
 5   ohe__work_type_Student               15000 non-null  float64
 6   remainder__number_of_decisions_made  15000 non-null  float64
 7   remainder__context_switch_count      15000 non-null  float64
 8   remainder__notifications_received    15000 non-null  float64
 9   remainder__screen_time_min           15000 non-null  float64
 10  remainder__deep_work_min             15000 non-null  float64
 11  remainder__task_complexity_avg       15000 non-null  float64
 12  remainder__caffeine_mg               15000 non-null  float64
 13  remainder__break_frequency           15000 non-null  float64
 14  remainder__sleep_hours               15000 non-null  float64
 15  remainder__deep_sleep_pct            15000 non-null  float64
 16  remainder__hydration_l               15000 non-null  float64
 17  remainder__noise_level_db            15000 non-null  float64
 18  remainder__temperature_c             15000 non-null  float64
 19  remainder__workload_score            15000 non-null  float64
 20  remainder__mental_tiredness_score    15000 non-null  float64
dtypes: float64(21)
memory usage: 2.4 MB

In [6]:
df.columns

Index(['ord_mood__mood', 'ord_env__work_environment', 'ohe__work_type_Manual',
       'ohe__work_type_Office', 'ohe__work_type_Remote',
       'ohe__work_type_Student', 'remainder__number_of_decisions_made',
       'remainder__context_switch_count', 'remainder__notifications_received',
       'remainder__screen_time_min', 'remainder__deep_work_min',
       'remainder__task_complexity_avg', 'remainder__caffeine_mg',
       'remainder__break_frequency', 'remainder__sleep_hours',
       'remainder__deep_sleep_pct', 'remainder__hydration_l',
       'remainder__noise_level_db', 'remainder__temperature_c',
       'remainder__workload_score', 'remainder__mental_tiredness_score'],
      dtype='str')

In [7]:
df.columns = [col.split('__')[-1] for col in df.columns]

In [8]:
X=df.drop("mental_tiredness_score",axis=1)
X.shape

(15000, 20)

In [9]:
y=df["mental_tiredness_score"]
y.shape

(15000,)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
df.head()

,mood,work_environment,work_type_Manual,work_type_Office,work_type_Remote,work_type_Student,number_of_decisions_made,context_switch_count,notifications_received,screen_time_min,...,task_complexity_avg,caffeine_mg,break_frequency,sleep_hours,deep_sleep_pct,hydration_l,noise_level_db,temperature_c,workload_score,mental_tiredness_score
0,2.0,1.0,0.0,0.0,1.0,0.0,-0.926224,2.120693,0.620176,-0.775544,...,0.763712,0.061978,-1.488002,0.729944,1.297849,0.229127,0.597886,-1.078432,-1.235038,22.17
1,0.0,2.0,0.0,0.0,1.0,0.0,0.176518,0.358696,0.127210,-0.335477,...,0.508233,-0.594295,-0.496573,0.220741,-0.201019,-0.105987,-0.916355,-1.449124,-0.565300,25.35
2,2.0,0.0,0.0,1.0,0.0,0.0,-0.650538,-1.403301,-1.228447,0.626205,...,2.296586,0.569898,0.494855,-1.059983,1.470731,0.039714,-0.601312,1.145723,1.134804,34.36
3,2.0,0.0,1.0,0.0,0.0,0.0,-0.650538,0.006296,-2.460862,-0.012957,...,-0.360396,0.421545,-0.992288,1.216002,-2.607937,-0.003996,-0.072852,0.269541,-0.153154,11.92
4,2.0,1.0,1.0,0.0,0.0,0.0,-2.304651,0.006296,0.373693,-0.452290,...,1.274670,0.693107,-0.000859,0.452197,0.361266,0.753653,1.329600,0.404338,1.443914,37.45

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((12000, 20), (3000, 20), (12000,), (3000,))

### Step 1: Feature Engineering

In [14]:
X_train["workload_per_hour"] = (
    X_train["workload_score"] /
    X_train["sleep_hours"]
)

X_test["workload_per_hour"] = (
    X_test["workload_score"] /
    X_test["sleep_hours"]
)

In [15]:
X_train["screen_to_sleep"] = (
    X_train["screen_time_min"] /
    X_train["sleep_hours"]
)

X_test["screen_to_sleep"] = (
    X_test["screen_time_min"] /
    X_test["sleep_hours"]
)

### Step 2: Feature Selection

In [16]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(
    random_state=42
)
rf.fit(X_train, y_train)
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf.feature_importances_
})
importance.sort_values(
    by="Importance",
    ascending=False
)

                     Feature  Importance
19            workload_score    0.210849
11       task_complexity_avg    0.180049
17            noise_level_db    0.086961
14               sleep_hours    0.070528
9            screen_time_min    0.067691
15            deep_sleep_pct    0.057749
0                       mood    0.050088
10             deep_work_min    0.046392
16               hydration_l    0.042014
21           screen_to_sleep    0.025435
20         workload_per_hour    0.025324
13           break_frequency    0.022986
6   number_of_decisions_made    0.021445
7       context_switch_count    0.021324
12               caffeine_mg    0.019997
18             temperature_c    0.019257
8     notifications_received    0.016429
1           work_environment    0.005439
3           work_type_Office    0.002954
5          work_type_Student    0.002452
2           work_type_Manual    0.002368
4           work_type_Remote    0.002269

In [17]:
cols_to_drop = [
    'work_environment',
    'work_type_Office',
    'work_type_Student',
    'work_type_Manual',
    'work_type_Remote'
]
X_train_fs = X_train.drop(columns=cols_to_drop)
X_test_fs = X_test.drop(columns=cols_to_drop)

In [18]:
X_train_fs.columns

Index(['mood', 'number_of_decisions_made', 'context_switch_count',
       'notifications_received', 'screen_time_min', 'deep_work_min',
       'task_complexity_avg', 'caffeine_mg', 'break_frequency', 'sleep_hours',
       'deep_sleep_pct', 'hydration_l', 'noise_level_db', 'temperature_c',
       'workload_score', 'workload_per_hour', 'screen_to_sleep'],
      dtype='str')

###   Step 3: Hyperparameter Tuning

In [25]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

params = {
    "alpha": [0.01, 0.1, 1, 10, 100]
}

grid = GridSearchCV(
    Ridge(),
    params,
    cv=5,
    scoring="r2"
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'alpha': 10}
Best CV Score: 0.7565700650983419

### Step 4: Final Model

In [26]:
best_rf = grid.best_estimator_
best_rf.fit(X_train, y_train)

Ridge(alpha=10)

### Step 5: Final Evaluation

In [27]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

pred = best_rf.predict(X_test)

print("MAE:", mean_absolute_error(y_test,pred))
print("RMSE:", mean_squared_error(y_test,pred)**0.5)
print("R2:", r2_score(y_test,pred))

MAE: 4.686476405328654
RMSE: 5.89614381175467
R2: 0.7667182776389461

###   Step 6: Model Serialization

In [29]:
import pickle
with open("final_mental_tiredness_model.pkl","wb") as f:
    pickle.dump(best_rf,f)